"""
Mirabaud Research Portal - Local Web Server
==========================================
URL: http://localhost:8000
Usage: python start_server.py

Routing: /z/<folder>/<filename> -> Z:\<folder>\<filename>
Example: /z/Initiations HC/Apple - High Conviction 2025.pdf
         /z/Latest Publications/1. Equity High Convictions.pdf
         /z/Wednesday Investment Meeting/WIM_2026_04_07.pdf
"""

import http.server
import socketserver
import webbrowser
import os
import sys
import mimetypes
from urllib.parse import unquote

PORT = 8000
HOST = "localhost"
Z_DRIVE = r"Z:"
WIM_FOLDER = r"G:\IT Project\ServeurWeb\pdfs\WIM & FOREX"
FOREX_FOLDER = r"G:\IT Project\ServeurWeb\pdfs\WIM & FOREX"

# Research publication folders (G: drive)
FOCUS_STOCKS_FOLDER = r"G:\Advisory\03. SELECTION ACTIONS\3.Daily\Focus Stocks\Done\EN Version"
THEMATICS_EN_FOLDER = r"G:\Advisory\03. SELECTION ACTIONS\3.Daily\Themes\Archive\EN Version"
WEEK_AHEAD_FOLDER = r"G:\IT Project\ServeurWeb\pdfs\The Week Ahead"
TREND_ALERT_FOLDER = r"G:\IT Project\ServeurWeb\pdfs\Trend Alert"
IDEAS_FOLDER = r"G:\IT Project\ServeurWeb\pdfs\Ideas"

# Quant Ranking data (BBG RAW CSV for Equity Helicopter View)
BBG_RAW_FILE = r"G:\Advisory\36.QUANT\1.Claude\Quant Ranking\BBG RAW Test.csv"

# Bloomberg RISK files (for price fallback)
# Bloomberg RISK files
# Source: SFTP Bloomberg data drop via the shared ESG Technical Dev folder
RISK_ACT_FILE = r"\\entad.net\FS\CH01\Common\ESG\Technical Dev\SFTP_Data\Mirabaud\RISK_ACT.csv"
RISK_OBL_FILE = r"\\entad.net\FS\CH01\Common\ESG\Technical Dev\SFTP_Data\Mirabaud\RISK_OBL.csv"

# Qualitative Scoring file (for Equity Helicopter View modal)
QUALITATIVE_FILE = r"G:\IT Project\ServeurWeb\excel\qualitative.xlsx"

# Structured Products weekly Run file (from Vontobel)
SP_RUN_FILE = r"G:\IT Project\ServeurWeb\excel\Run produits structurés - Vontobel.xlsx"
SP_RUN_PDF = r"G:\IT Project\ServeurWeb\pdfs\Structured Products\run.pdf"
SP_ONEPAGER_COMMODITIES = r"G:\IT Project\ServeurWeb\pdfs\SP\One Pager 90% Capital guranteed autocall on Commodities.pdf"

# CFRA trading item ID mapping (ISIN -> tradingItemId from S&P Capital IQ)
# Generated by build_cfra_ids.py from cfra_tradingid.xlsx
CFRA_IDS_FILE = "cfra_ids.json"

script_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(script_dir)


class MirabaudHandler(http.server.SimpleHTTPRequestHandler):

    def do_GET(self):
        path = unquote(self.path)

        # /wim/<filename> -> G:\IT Project\ServeurWeb\pdfs\WIM & FOREX\<filename>
        if path.startswith('/wim/'):
            filepath = os.path.join(WIM_FOLDER, path[5:])
            if os.path.isfile(filepath):
                self._serve_file(filepath)
            else:
                self.send_error(404, f"WIM not found: {path[5:]}")
            return

        # /forex/<filename> -> G:\IT Project\ServeurWeb\pdfs\WIM & FOREX\<filename>
        if path.startswith('/forex/'):
            filepath = os.path.join(FOREX_FOLDER, path[7:])
            if os.path.isfile(filepath):
                self._serve_file(filepath)
            else:
                self.send_error(404, f"Forex not found: {path[7:]}")
            return

        # /sp-doc/{ISIN}/{type} -> search Doc folders for matching file
        # type: kid, ts (term sheet), op (one pager)
        if path.startswith('/sp-doc/'):
            parts = path[8:].split('/')
            if len(parts) >= 2:
                isin = parts[0]
                dtype = parts[1].lower()
                found = self._find_sp_doc(isin, dtype)
                if found:
                    self._serve_file(found)
                else:
                    self.send_error(404, f"SP doc not found: {isin}/{dtype}")
            else:
                self.send_error(400, "Usage: /sp-doc/{ISIN}/kid or /sp-doc/{ISIN}/ts")
            return

        # /z/focus-stocks/<filename> -> smart search in Focus Stocks folder tree
        if path.startswith('/z/focus-stocks/'):
            found = self._smart_find(FOCUS_STOCKS_FOLDER, path[16:])
            if found:
                self._serve_file(found)
            else:
                self.send_error(404, f"Focus Stock not found: {path[16:]}")
            return

        # /z/thematics-en/<filename> -> smart search in Themes EN folder tree
        if path.startswith('/z/thematics-en/'):
            found = self._smart_find(THEMATICS_EN_FOLDER, path[16:])
            if found:
                self._serve_file(found)
            else:
                self.send_error(404, f"Thematic not found: {path[16:]}")
            return

        # /z/week-ahead/<filename> -> smart search in Week Ahead folder tree
        if path.startswith('/z/week-ahead/'):
            found = self._smart_find(WEEK_AHEAD_FOLDER, path[14:], extra_exts=['.pptx', '.ppt'])
            if found:
                self._serve_file(found)
            else:
                self.send_error(404, f"Week Ahead not found: {path[14:]}")
            return

        # /z/trend-alert/<filename> -> smart search in pdfs folder tree
        if path.startswith('/z/trend-alert/'):
            found = self._smart_find(TREND_ALERT_FOLDER, path[15:])
            if found:
                self._serve_file(found)
            else:
                self.send_error(404, f"Trend Alert not found: {path[15:]}")
            return

        # /z/ideas/<filename> -> smart search in pdfs\Ideas folder tree
        if path.startswith('/z/ideas/'):
            found = self._smart_find(IDEAS_FOLDER, path[9:])
            if found:
                self._serve_file(found)
            else:
                self.send_error(404, f"Idea not found: {path[9:]}")
            return

        # /share-pdf?path=/z/...&title=... -> open Outlook with PDF attached (Windows only)
        if path.startswith('/share-pdf'):
            self._handle_share_pdf()
            return

        # /data/bbg-raw -> G:\Advisory\36.QUANT\1.Claude\Quant Ranking\BBG RAW Test.csv
        # Served with CORS header so the Equity Helicopter View can fetch() it
        if path == '/data/bbg-raw':
            if os.path.isfile(BBG_RAW_FILE):
                self._serve_file(BBG_RAW_FILE, cors=True, ctype_override='text/csv; charset=utf-8')
            else:
                self.send_error(404, f"BBG RAW CSV not found at {BBG_RAW_FILE}")
            return

        # /data/risk-act -> \\entad.net\...\RISK_ACT.csv (equities)
        # Used as price fallback when BBG RAW has #N/A for some stocks
        if path == '/data/risk-act':
            if os.path.isfile(RISK_ACT_FILE):
                self._serve_file(RISK_ACT_FILE, cors=True, ctype_override='text/csv; charset=utf-8')
            else:
                self.send_error(404, f"RISK_ACT CSV not found at {RISK_ACT_FILE}")
            return

        # /data/risk-obl -> \\entad.net\...\RISK_OBL.csv (bonds)
        # Used by Fixed Income screener for bond-level data
        if path == '/data/risk-obl':
            if os.path.isfile(RISK_OBL_FILE):
                self._serve_file(RISK_OBL_FILE, cors=True, ctype_override='text/csv; charset=utf-8')
            else:
                self.send_error(404, f"RISK_OBL CSV not found at {RISK_OBL_FILE}")
            return

        # /data/qualitative -> G:\IT Project\ServeurWeb\excel\qualitative.xlsx
        # Parsed client-side via SheetJS for the Equity Helicopter stock modal
        if path == '/data/qualitative':
            if os.path.isfile(QUALITATIVE_FILE):
                self._serve_file(QUALITATIVE_FILE, cors=True,
                                 ctype_override='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            else:
                self.send_error(404, f"Qualitative file not found at {QUALITATIVE_FILE}")
            return

        # /api/publications -> scans the 4 research folders and returns JSON list of all PDFs
        # Parses filenames to extract date + title. Used by portal.html (Latest Research)
        # and research.html (full library). Auto-refreshes when files change in folders.
        if path == '/api/publications':
            self._serve_publications()
            return

        # /api/universe -> reads Equity_Investment_Universe__Freezed.xlsx (sheet CFRA Universe)
        # and returns a JSON dict {ticker: {name, sector, isin, country, region}}.
        # Used by portal.html to filter FMP earnings to tickers the bank actually covers,
        # and to enrich each card with full name + sector.
        if path == '/api/universe':
            self._serve_universe()
            return

        # /logo/<domain> -> server-side proxy for Google's favicon CDN, so the client
        # can <img src="/logo/apple.com"> without cross-origin issues. This enables the
        # PDF export to capture the logo via a same-origin canvas.
        if path.startswith('/logo/'):
            import urllib.request, urllib.parse
            domain = urllib.parse.unquote(path[6:]).strip().strip('/')
            if not domain or '/' in domain or '\\' in domain or len(domain) > 120:
                self.send_error(400, 'Invalid domain')
                return
            try:
                upstream = 'https://www.google.com/s2/favicons?domain=' + urllib.parse.quote(domain) + '&sz=64'
                req = urllib.request.Request(upstream, headers={'User-Agent': 'Mirabaud-Portal/1.0'})
                with urllib.request.urlopen(req, timeout=4) as r:
                    body = r.read()
                    ctype = r.headers.get('Content-Type', 'image/png')
                self.send_response(200)
                self.send_header('Content-Type', ctype)
                self.send_header('Access-Control-Allow-Origin', '*')
                self.send_header('Cache-Control', 'public, max-age=86400')
                self.send_header('Content-Length', str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            except Exception as e:
                self.send_error(502, f'Favicon proxy failed: {e}')
            return

        # /data/focus-stocks-index -> JSON mapping of Focus Stock PDFs by detected name token
        # Scans FOCUS_STOCKS_FOLDER (G: drive). Returns the MOST RECENT PDF per matched entity.
        # The frontend cross-references this with each row's company name/ticker.
        #   Returned shape : { "files": [ { "filename": "...", "mtime_iso": "...", "size": int }, ... ] }
        # The frontend does the actual name matching via substring on company name, so this route
        # stays simple and format-agnostic.
        if path == '/data/focus-stocks-index':
            import json as _json
            out = { "folder": FOCUS_STOCKS_FOLDER, "exists": False, "files": [] }
            try:
                if os.path.isdir(FOCUS_STOCKS_FOLDER):
                    out["exists"] = True
                    for root, _dirs, files in os.walk(FOCUS_STOCKS_FOLDER):
                        for fn in files:
                            if fn.lower().endswith('.pdf'):
                                fp = os.path.join(root, fn)
                                try:
                                    st = os.stat(fp)
                                    out["files"].append({
                                        "filename": fn,
                                        "rel_path": os.path.relpath(fp, FOCUS_STOCKS_FOLDER).replace('\\', '/'),
                                        "mtime": st.st_mtime,
                                        "size": st.st_size,
                                    })
                                except OSError:
                                    pass
                    # Sort newest first
                    out["files"].sort(key=lambda x: x["mtime"], reverse=True)
            except Exception as e:
                out["error"] = str(e)
            body = _json.dumps(out).encode('utf-8')
            self.send_response(200)
            self.send_header('Content-Type', 'application/json; charset=utf-8')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.send_header('Content-Length', str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return

        # /data/cfra-ids -> cfra_ids.json (ISIN -> CFRA tradingItemId)
        # Used by equity.html and equity_heli.html to show a CFRA button in Docs column.
        # Regenerate cfra_ids.json by running build_cfra_ids.py after updating cfra_tradingid.xlsx.
        if path == '/data/cfra-ids':
            import json as _json
            cfra_path = os.path.join(script_dir, CFRA_IDS_FILE)
            try:
                with open(cfra_path, 'rb') as f:
                    body = f.read()
                self.send_response(200)
                self.send_header('Content-Type', 'application/json; charset=utf-8')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.send_header('Cache-Control', 'max-age=3600')
                self.send_header('Content-Length', str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            except FileNotFoundError:
                # Return empty map so the front-end keeps working without buttons
                body = b'{}'
                self.send_response(200)
                self.send_header('Content-Type', 'application/json; charset=utf-8')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.send_header('Content-Length', str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            except Exception as e:
                err = _json.dumps({"error": str(e)}).encode('utf-8')
                self.send_response(500)
                self.send_header('Content-Type', 'application/json; charset=utf-8')
                self.send_header('Content-Length', str(len(err)))
                self.end_headers()
                self.wfile.write(err)
            return

        # /data/sp-run -> G:\IT Project\ServeurWeb\excel\Run produits structures - Vontobel.xlsx
        # Weekly Structured Products Run (parsed client-side via SheetJS)
        if path == '/data/sp-run':
            if os.path.isfile(SP_RUN_FILE):
                self._serve_file(SP_RUN_FILE, cors=True,
                                 ctype_override='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            else:
                self.send_error(404, f"SP Run file not found at {SP_RUN_FILE}")
            return

        # /data/sp-run-pdf -> G:\IT Project\ServeurWeb\pdfs\SP\run.pdf
        # The PDF version of the weekly Run (for direct viewing)
        if path == '/data/sp-run-pdf':
            if os.path.isfile(SP_RUN_PDF):
                self._serve_file(SP_RUN_PDF, cors=True, ctype_override='application/pdf')
            else:
                self.send_error(404, f"SP Run PDF not found at {SP_RUN_PDF}")
            return

        # /data/sp-onepager-commodities -> One Pager 90% Capital guaranteed autocall on Commodities.pdf
        if path == '/data/sp-onepager-commodities':
            if os.path.isfile(SP_ONEPAGER_COMMODITIES):
                self._serve_file(SP_ONEPAGER_COMMODITIES, cors=True, ctype_override='application/pdf')
            else:
                self.send_error(404, f"SP One Pager Commodities not found at {SP_ONEPAGER_COMMODITIES}")
            return

        # /data/sp-run-pdf -> G:\IT Project\ServeurWeb\pdfs\Structured Products\run.pdf
        # Printable PDF version of the weekly Run
        if path == '/data/sp-run-pdf':
            if os.path.isfile(SP_RUN_PDF):
                self._serve_file(SP_RUN_PDF, cors=True, ctype_override='application/pdf')
            else:
                self.send_error(404, f"SP Run PDF not found at {SP_RUN_PDF}")
            return

        # /z/<anything> -> Z:\<anything>  with smart fallback for the "Initiations HC" folder
        # (so HC_PDFS mappings survive year renames like "NVIDIA - HC 2025" -> "...2026").
        if path.startswith('/z/'):
            zpath = path[3:]
            filepath = os.path.join(Z_DRIVE, zpath.replace('/', os.sep))
            if os.path.isfile(filepath):
                self._serve_file(filepath)
                return
            # Smart fallback : for Initiations HC or ESG SRI folders, if the requested
            # filename is not found, try to match by the prefix before " - High Conviction"
            # or before " ESG Report". E.g. "NVIDIA - High Conviction 2025.pdf" finds
            # "NVIDIA - High Conviction 2026.pdf" on disk.
            parts = zpath.split('/')
            if len(parts) >= 2:
                folder = os.path.join(Z_DRIVE, *parts[:-1])
                wanted = parts[-1]
                if os.path.isdir(folder):
                    # Extract company stem (token before " - " or " ESG Report")
                    stem = wanted
                    for sep in [' - ', ' ESG Report']:
                        if sep in stem:
                            stem = stem.split(sep, 1)[0]
                            break
                    stem_u = stem.strip().upper()
                    if stem_u:
                        try:
                            candidates = [f for f in os.listdir(folder)
                                          if f.lower().endswith('.pdf') and f.upper().startswith(stem_u)]
                        except OSError:
                            candidates = []
                        if candidates:
                            # Pick the most recent file by mtime
                            candidates.sort(key=lambda f: os.path.getmtime(os.path.join(folder, f)), reverse=True)
                            self._serve_file(os.path.join(folder, candidates[0]))
                            return
            self.send_error(404, f"Z: not found: {zpath}")
            return

        super().do_GET()

    def _handle_share_pdf(self):
        """Open Outlook with the requested PDF attached (Windows/COM)."""
        import subprocess
        # Parse the query manually to ensure UTF-8 decoding (parse_qs defaults to latin-1)
        q = self.path.split('?', 1)[1] if '?' in self.path else ''
        params = {}
        for pair in q.split('&'):
            if '=' in pair:
                k, v = pair.split('=', 1)
                params[k] = unquote(v)
        raw_path = params.get('path', '')
        title    = params.get('title', 'Document')
        summary  = params.get('summary', '')
        if not raw_path:
            self.send_error(400, "Missing 'path' parameter")
            return

        # Resolve virtual /z/... or /sp-doc/... /wim/... /forex/... to a real file
        real_path = self._resolve_virtual_path(raw_path)
        if not real_path or not os.path.isfile(real_path):
            self.send_error(404, f"File not found: {raw_path}")
            return

        # Build the HTML email body from the AI summary
        html_body = self._build_email_html(title, summary)

        # Build a PowerShell script that drives Outlook via COM with HTMLBody
        # Use EncodedCommand (UTF-16LE base64) to bypass all shell escaping issues with Unicode chars
        import base64
        safe_path  = real_path.replace("'", "''")
        safe_title = title.replace("'", "''")
        # PowerShell here-string @' ... '@ keeps the HTML literal (no escape needed inside)
        # We use a unique sentinel to delimit the HTML so single quotes inside are safe
        safe_html = html_body.replace("'", "''")
        ps_script = (
            "try { "
            "$o = New-Object -ComObject Outlook.Application; "
            "$m = $o.CreateItem(0); "
            f"$m.Subject = 'Mirabaud Research | {safe_title}'; "
            f"$m.HTMLBody = '{safe_html}'; "
            f"$m.Attachments.Add('{safe_path}') | Out-Null; "
            "$m.Display($false); "
            "Write-Output 'OK' "
            "} catch { Write-Error $_.Exception.Message; exit 1 }"
        )
        encoded = base64.b64encode(ps_script.encode('utf-16-le')).decode('ascii')
        try:
            # Run synchronously with timeout so we can capture errors
            result = subprocess.run(
                ['powershell', '-NoProfile', '-EncodedCommand', encoded],
                capture_output=True, text=True, timeout=30
            )
            print(f"  [share-pdf] PowerShell exit={result.returncode}")
            if result.stdout: print(f"  [share-pdf] stdout: {result.stdout.strip()}")
            if result.stderr: print(f"  [share-pdf] stderr: {result.stderr.strip()}")
            if result.returncode != 0:
                err = (result.stderr or result.stdout or 'Unknown error').strip()
                self.send_response(500)
                self.send_header('Content-Type', 'text/plain; charset=utf-8')
                self.end_headers()
                self.wfile.write(err.encode('utf-8', errors='replace'))
                return
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(b'{"status":"ok"}')
        except subprocess.TimeoutExpired:
            self.send_error(500, "Outlook took too long to respond (timeout)")
        except Exception as e:
            print(f"  [share-pdf] Exception: {e}")
            self.send_error(500, f"Outlook failed: {e}")

    def _build_email_html(self, title, summary):
        """Build a clean HTML email body from the AI summary (plain text or already-rendered text)."""
        import html
        import re

        # The summary comes from innerText of the modal, so it's plain text.
        # Bullets show up as lines starting with the bullet glyph (already rendered by the browser).
        # Format: line 1 = intro paragraph; subsequent lines may be bullets.
        title_safe = html.escape(title or 'Document')
        summary = (summary or '').strip()

        body_html = ''
        if summary:
            # Split into "blocks" separated by blank lines
            paragraphs = []
            bullets = []
            in_bullets = False
            for raw_line in summary.split('\n'):
                line = raw_line.strip()
                if not line:
                    continue
                # Bullets: line starts with •, -, *, or already has a bullet character
                if re.match(r'^[•\-\*\u2022]\s', line) or (line.startswith('•') and len(line) > 1):
                    bullet_text = re.sub(r'^[•\-\*\u2022]\s*', '', line)
                    bullets.append(html.escape(bullet_text))
                    in_bullets = True
                else:
                    if in_bullets:
                        # Close current bullet group before starting a new paragraph
                        if bullets:
                            paragraphs.append(('ul', bullets))
                            bullets = []
                        in_bullets = False
                    paragraphs.append(('p', html.escape(line)))
            if bullets:
                paragraphs.append(('ul', bullets))

            for kind, content in paragraphs:
                if kind == 'p':
                    body_html += f'<p style="margin:0 0 12px 0;font-family:Calibri,Arial,sans-serif;font-size:11pt;color:#1d3550;line-height:1.5">{content}</p>'
                else:
                    body_html += '<ul style="margin:0 0 14px 0;padding-left:22px;font-family:Calibri,Arial,sans-serif;font-size:11pt;color:#1d3550;line-height:1.5">'
                    for b in content:
                        body_html += f'<li style="margin-bottom:5px">{b}</li>'
                    body_html += '</ul>'

        # Compose the full email HTML
        return f'''<html><body style="font-family:Calibri,Arial,sans-serif;font-size:11pt;color:#1d3550;line-height:1.5">
<p style="margin:0 0 14px 0">Dear,</p>
<p style="margin:0 0 14px 0">Please find below a brief summary of <strong>{title_safe}</strong>, with the full document attached.</p>
<div style="border-left:3px solid #bc9654;padding:6px 14px;margin:0 0 16px 0;background:#f8f9fb">
{body_html if body_html else '<p style="margin:0">See attached document for details.</p>'}
</div>
<p style="margin:0 0 14px 0">Best regards,</p>
<p style="margin:0;color:#6b8097;font-size:9pt;font-style:italic">Mirabaud &amp; Cie SA &middot; WM Financial Research</p>
</body></html>'''

    def _resolve_virtual_path(self, vpath):
        """Map a server URL path (/z/..., /wim/..., /sp-doc/...) to a Windows file path."""
        if vpath.startswith('/wim/'):
            p = os.path.join(WIM_FOLDER, vpath[5:])
            return p if os.path.isfile(p) else None
        if vpath.startswith('/forex/'):
            p = os.path.join(FOREX_FOLDER, vpath[7:])
            return p if os.path.isfile(p) else None
        if vpath.startswith('/sp-doc/'):
            parts = vpath[8:].split('/')
            if len(parts) >= 2:
                return self._find_sp_doc(parts[0], parts[1].lower())
            return None
        if vpath.startswith('/z/focus-stocks/'):
            return self._smart_find(FOCUS_STOCKS_FOLDER, vpath[16:])
        if vpath.startswith('/z/thematics-en/'):
            return self._smart_find(THEMATICS_EN_FOLDER, vpath[16:])
        if vpath.startswith('/z/week-ahead/'):
            return self._smart_find(WEEK_AHEAD_FOLDER, vpath[14:], extra_exts=['.pptx', '.ppt'])
        if vpath.startswith('/z/trend-alert/'):
            return self._smart_find(TREND_ALERT_FOLDER, vpath[15:])
        if vpath.startswith('/z/ideas/'):
            return self._smart_find(IDEAS_FOLDER, vpath[9:])
        if vpath.startswith('/z/'):
            p = os.path.join(Z_DRIVE, vpath[3:].replace('/', os.sep))
            return p if os.path.isfile(p) else None
        return None

    def _serve_universe(self):
        """Return the pre-generated investment universe from universe.json.
        The JSON file is built from Equity_Investment_Universe__Freezed.xlsx and
        shipped alongside start_server.py. To rebuild after an xlsx change, run
        rebuild_universe.py (provided separately) or regenerate universe.json.
        """
        import json
        json_path = os.path.join(script_dir, "universe.json")
        if not os.path.isfile(json_path):
            payload = json.dumps({
                "universe": {},
                "count": 0,
                "error": "universe.json not found next to start_server.py",
            }).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            self.wfile.write(payload)
            return
        try:
            with open(json_path, "rb") as f:
                data = f.read()
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(data)))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            self.wfile.write(data)
        except Exception as e:
            self.send_error(500, f"Failed to read universe.json: {e}")

    def _serve_publications(self):
        """Scan the 4 publication folders and return a JSON list of all PDFs
        with parsed date and title. Used by portal.html (Latest Research carousel)
        and research.html (full filterable library).
        """
        import re
        import json
        from datetime import datetime

        # ─── Filename parsers ────────────────────────────────────
        # Returns (iso_date, clean_title) or (None, None) if no match

        def parse_dotted(fn):
            # "2026.04.10 - Hermes EN.pdf"
            m = re.match(r'^(\d{4})\.(\d{2})\.(\d{2})\s*-\s*(.+?)(?:\s+EN)?\.pdf$', fn, re.IGNORECASE)
            if m:
                y, mo, d, title = m.group(1), m.group(2), m.group(3), m.group(4)
                return f"{y}-{mo}-{d}", title.strip()
            return None, None

        def parse_compact(fn):
            # "20251014-Thermo Fisher-EN.pdf" or "20251014-Title-EN.pdf"
            m = re.match(r'^(\d{4})(\d{2})(\d{2})\s*-\s*(.+?)(?:-EN|\s+EN)?\.pdf$', fn, re.IGNORECASE)
            if m:
                y, mo, d, title = m.group(1), m.group(2), m.group(3), m.group(4)
                title = re.sub(r'-EN$', '', title, flags=re.IGNORECASE).strip()
                return f"{y}-{mo}-{d}", title
            return None, None

        def parse_week_ahead(fn):
            # Usually: "{uuid}-13.04.2026 - Week ahead EN.pdf" or "13.04.2026 - Week ahead EN.pdf"
            m = re.search(r'(\d{2})\.(\d{2})\.(\d{4})', fn)
            if m:
                d, mo, y = m.group(1), m.group(2), m.group(3)
                return f"{y}-{mo}-{d}", "The Week Ahead"
            return None, None

        def parse_trend_alert(fn):
            # "Trend Alert - 13 Apr 2026.pdf"
            m = re.match(r'^Trend Alert\s*-\s*(\d{1,2})\s+(\w+)\s+(\d{4})\.pdf$', fn, re.IGNORECASE)
            if m:
                d, mon_name, y = m.group(1), m.group(2), m.group(3)
                months = {'jan':'01','feb':'02','mar':'03','apr':'04','may':'05','jun':'06',
                          'jul':'07','aug':'08','sep':'09','oct':'10','nov':'11','dec':'12',
                          'january':'01','february':'02','march':'03','april':'04',
                          'june':'06','july':'07','august':'08','september':'09',
                          'october':'10','november':'11','december':'12'}
                mo = months.get(mon_name.lower()[:3], '01')
                return f"{y}-{mo}-{d.zfill(2)}", "Trend Alert"
            return None, None

        # ─── Scan all 4 folders ──────────────────────────────────
        pubs = []
        folder_configs = [
            (FOCUS_STOCKS_FOLDER,  'Focus Stock',  '/z/focus-stocks/',  [parse_dotted, parse_compact]),
            (THEMATICS_EN_FOLDER,  'Thematic',     '/z/thematics-en/',  [parse_dotted, parse_compact]),
            (WEEK_AHEAD_FOLDER,    'Week Ahead',   '/z/week-ahead/',    [parse_week_ahead]),
            (TREND_ALERT_FOLDER,   'Trend Alert',  '/z/trend-alert/',   [parse_trend_alert]),
        ]
        for folder, doc_type, route, parsers in folder_configs:
            if not os.path.isdir(folder):
                continue
            for root, dirs, files in os.walk(folder):
                for fn in files:
                    if not fn.lower().endswith('.pdf'):
                        continue
                    # Try each parser until one matches
                    iso_date, title = None, None
                    for parser in parsers:
                        iso_date, title = parser(fn)
                        if iso_date:
                            break
                    if not iso_date:
                        continue  # Skip files we can't parse a date from
                    pubs.append({
                        'date':  iso_date,
                        'title': title,
                        'type':  doc_type,
                        'pdf':   route + fn,
                        'file':  fn,
                    })

        # Sort by date descending (most recent first)
        pubs.sort(key=lambda p: p['date'], reverse=True)

        payload = json.dumps({'count': len(pubs), 'publications': pubs}).encode('utf-8')
        self.send_response(200)
        self.send_header('Content-Type', 'application/json; charset=utf-8')
        self.send_header('Content-Length', str(len(payload)))
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Cache-Control', 'no-cache')
        self.end_headers()
        self.wfile.write(payload)

    def _serve_file(self, filepath, cors=False, ctype_override=None):
        try:
            if ctype_override:
                ctype = ctype_override
            else:
                ctype, _ = mimetypes.guess_type(filepath)
                ctype = ctype or 'application/octet-stream'
            with open(filepath, 'rb') as f:
                data = f.read()
            self.send_response(200)
            self.send_header('Content-Type', ctype)
            self.send_header('Content-Length', str(len(data)))
            if cors:
                self.send_header('Access-Control-Allow-Origin', '*')
                self.send_header('Cache-Control', 'no-cache')
            self.end_headers()
            self.wfile.write(data)
        except Exception as e:
            self.send_error(500, str(e))

    def _smart_find(self, base_folder, requested_name, extra_exts=None):
        """Smart file finder: exact match first, then recursive search.
        
        Strategy:
        1. Try exact path: base_folder/requested_name
        2. Walk the folder tree looking for files that match the requested name
        3. If no exact match, try fuzzy: look for files containing key parts of the name
        4. For extra_exts, also try replacing .pdf with those extensions
        """
        if not os.path.isdir(base_folder):
            return None
        
        # 1. Exact match
        exact = os.path.join(base_folder, requested_name)
        if os.path.isfile(exact):
            return exact
        
        # 2. Try with extra extensions (e.g. .pptx instead of .pdf)
        if extra_exts:
            name_no_ext = os.path.splitext(requested_name)[0]
            for ext in extra_exts:
                alt = os.path.join(base_folder, name_no_ext + ext)
                if os.path.isfile(alt):
                    return alt
        
        # 3. Recursive search: exact filename match OR filename contains target as substring
        target_name = os.path.basename(requested_name)
        target_lower = target_name.lower()
        for root, dirs, files in os.walk(base_folder):
            for fn in files:
                fn_lower = fn.lower()
                if fn_lower == target_lower or target_lower in fn_lower:
                    return os.path.join(root, fn)
        
        # 4. Fuzzy: extract core title words (strip dates, extensions, "EN")
        import re
        core = os.path.splitext(target_name)[0]  # strip .pdf/.pptx
        core = re.sub(r'^\d{4}\.\d{2}\.\d{2}\s*-\s*', '', core)  # strip "2026.04.10 - " prefix
        core = re.sub(r'\d{1,2}\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\w*\s+\d{4}', '', core, flags=re.IGNORECASE)  # strip "13 Apr 2026"
        core = re.sub(r'\d{1,2}\.\d{1,2}\.\d{4}', '', core)  # strip "13.04.2026"
        core = re.sub(r'\b(EN|FR)\b', '', core, flags=re.IGNORECASE)  # strip language codes
        core = re.sub(r'[-_\s]+', ' ', core).strip().lower()
        
        if len(core) > 2:
            best = None
            for root, dirs, files in os.walk(base_folder):
                for fn in files:
                    fn_lower = fn.lower()
                    if core in fn_lower and (fn_lower.endswith('.pdf') or fn_lower.endswith('.pptx') or fn_lower.endswith('.ppt') or
                        (extra_exts and any(fn_lower.endswith(e) for e in extra_exts))):
                        best = os.path.join(root, fn)
                        if ' en' in fn_lower or '_en' in fn_lower:
                            return best
            if best:
                return best
        
        # 5. Last resort: search by first significant word (3+ chars)
        words = [w for w in core.split() if len(w) >= 3 and w not in ('the', 'and', 'for')]
        if words:
            keyword = words[0]
            for root, dirs, files in os.walk(base_folder):
                for fn in files:
                    fn_lower = fn.lower()
                    if keyword in fn_lower and (fn_lower.endswith('.pdf') or fn_lower.endswith('.pptx') or fn_lower.endswith('.ppt')):
                        return os.path.join(root, fn)
        
        return None

    def _find_sp_doc(self, isin, dtype):
        """Search Doc5/Doc7/Doc12/Doc21/Doc22 for a file matching ISIN and type."""
        doc_folders = ['Doc5', 'Doc7', 'Doc12', 'Doc 21', 'Doc 22']
        for folder in doc_folders:
            fpath = os.path.join(Z_DRIVE, folder)
            if not os.path.isdir(fpath):
                continue
            for fn in os.listdir(fpath):
                if not fn.startswith(isin):
                    continue
                fn_lower = fn.lower()
                if dtype == 'kid' and ' kid ' in fn_lower and fn_lower.endswith('.pdf'):
                    return os.path.join(fpath, fn)
                elif dtype == 'ts' and ' kid ' not in fn_lower and fn_lower.endswith('.pdf'):
                    return os.path.join(fpath, fn)
                elif dtype == 'op' and 'one pager' in fn_lower and fn_lower.endswith('.pdf'):
                    return os.path.join(fpath, fn)
        return None

    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cache-Control", "no-cache")
        super().end_headers()

    def log_message(self, format, *args):
        print(f"  [{self.log_date_time_string()}]  {format % args}")


print("=" * 58)
print("  MIRABAUD RESEARCH PORTAL - Serveur local")
print("=" * 58)
print(f"  Dossier servi  : {script_dir}")
print(f"  Z: drive       : {Z_DRIVE}")
print(f"  URL            : http://{HOST}:{PORT}")
print(f"  Arret          : Ctrl + C")
print("-" * 58)

if os.path.isdir(Z_DRIVE):
    key = ['Latest Publications', 'Initiations HC', 'News Flow HC',
           'Wednesday Investment Meeting', 'Doc5', 'Doc7', 'Doc12', 'Doc 21', 'Doc 22']
    for k in key:
        kp = os.path.join(Z_DRIVE, k)
        if os.path.isdir(kp):
            c = len([f for f in os.listdir(kp) if f.lower().endswith('.pdf')])
            print(f"  /z/{k:30s} {c} PDFs")
else:
    print(f"  Z: INACCESSIBLE")

# Research publication folders (recursive count)
pub_routes = {
    '/z/focus-stocks/': FOCUS_STOCKS_FOLDER,
    '/z/thematics-en/': THEMATICS_EN_FOLDER,
    '/z/week-ahead/':   WEEK_AHEAD_FOLDER,
    '/z/trend-alert/':  TREND_ALERT_FOLDER,
    '/z/ideas/':        IDEAS_FOLDER,
}
for route, folder in pub_routes.items():
    if os.path.isdir(folder):
        c = 0
        for root, dirs, files in os.walk(folder):
            c += len([f for f in files if f.lower().endswith(('.pdf', '.pptx', '.ppt'))])
        print(f"  {route:30s} {c} files (recursive)")
    else:
        print(f"  {route:30s} NOT FOUND")

print("=" * 58, "\n")

webbrowser.open(f"http://{HOST}:{PORT}/portal.html")

try:
    with socketserver.TCPServer((HOST, PORT), MirabaudHandler) as httpd:
        httpd.allow_reuse_address = True
        httpd.serve_forever()
except KeyboardInterrupt:
    print("\n  Serveur arrete.")
    sys.exit(0)
except OSError:
    print(f"\n  ERREUR: Port {PORT} deja utilise.")
    input("  Appuie sur Entree pour quitter...")
    sys.exit(1)
